"""Local result storage & reporting for IPRMS (plan §9, Task 8).

Reporting is based entirely on the local artifacts under runs/<run_id>/ and on
run_summary.csv — NO Delta tables / cloud storage. This module:
  * validates each run artifact against its Pydantic schema (review/audit), and
  * produces a compact summary of a run (for demo reporting / re-run comparison).

metrics.json and run_summary.csv are generated by Agent H (Task 28); here we
confirm and validate them as part of the local reporting layer.
"""
from __future__ import annotations

import csv
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List

_REPO_ROOT = str(Path(__file__).resolve().parent)
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from schemas.artifact_schema import (
    AnomalyReport,
    BidThresholdCheck,
    PolicyCheck,
    SoleSourceCheck,
)
from schemas.decision_schema import (
    ApprovalPacket,
    ErpPostingResult,
    PODraft,
    RunMetrics,
)
from schemas.pr_schema import BudgetCheck, ExtractedPR, VendorMatch

# Artifact file -> validating schema.
SCHEMA_MAP = {
    "extracted_pr.json": ExtractedPR,
    "budget_check.json": BudgetCheck,
    "vendor_match.json": VendorMatch,
    "policy_check.json": PolicyCheck,
    "sole_source_check.json": SoleSourceCheck,
    "bid_threshold_check.json": BidThresholdCheck,
    "anomaly_report.json": AnomalyReport,
    "approval_packet.json": ApprovalPacket,
    "po_draft.json": PODraft,
    "metrics.json": RunMetrics,
    "erp_posting_result.json": ErpPostingResult,
}

# Markdown/CSV artifacts that must exist (not schema-validated, presence-checked).
TEXT_ARTIFACTS = ["exceptions.md", "audit_log.md", "run_summary.csv",
                  "context_packet.json", "evidence_index.json"]


@dataclass
class ArtifactStatus:
    artifact: str
    exists: bool
    valid: bool
    error: str = ""


@dataclass
class ReportResult:
    run_dir: Path
    all_valid: bool
    results: List[ArtifactStatus] = field(default_factory=list)


def validate_run(run_dir: Path | str) -> ReportResult:
    """Validate every schema-backed artifact + confirm text artifacts exist."""
    run_dir = Path(run_dir)
    results: List[ArtifactStatus] = []

    for name, model in SCHEMA_MAP.items():
        p = run_dir / name
        if not p.exists():
            results.append(ArtifactStatus(name, False, False, "missing"))
            continue
        try:
            model.model_validate_json(p.read_text(encoding="utf-8"))
            results.append(ArtifactStatus(name, True, True))
        except Exception as e:  # noqa: BLE001 - report validation error verbatim
            results.append(ArtifactStatus(name, True, False, f"{type(e).__name__}: {e}"))

    for name in TEXT_ARTIFACTS:
        exists = (run_dir / name).exists()
        results.append(ArtifactStatus(name, exists, exists, "" if exists else "missing"))

    all_valid = all(r.valid for r in results)
    return ReportResult(run_dir=run_dir, all_valid=all_valid, results=results)


def summarize_run(run_dir: Path | str) -> Dict[str, Any]:
    """Compact run summary for demo reporting (from run_summary.csv + metrics.json)."""
    run_dir = Path(run_dir)
    summary: Dict[str, Any] = {}

    csv_path = run_dir / "run_summary.csv"
    if csv_path.exists():
        with csv_path.open(encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
            if rows:
                summary["run_summary"] = rows[0]

    metrics_path = run_dir / "metrics.json"
    if metrics_path.exists():
        summary["metrics"] = json.loads(metrics_path.read_text(encoding="utf-8"))

    return summary


def _main(argv=None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Validate and summarize a local IPRMS run.")
    parser.add_argument("--run-dir", required=True, help="Path to runs/<run_id>/")
    args = parser.parse_args(argv)

    report = validate_run(args.run_dir)
    print(f"Run: {report.run_dir}")
    print("=" * 50)
    for r in report.results:
        flag = "OK  " if r.valid else "FAIL"
        print(f"[{flag}] {r.artifact}{('  -> ' + r.error) if r.error else ''}")
    print("=" * 50)
    print("RESULT:", "ALL VALID" if report.all_valid else "VALIDATION FAILED")

    summary = summarize_run(args.run_dir)
    if "run_summary" in summary:
        rs = summary["run_summary"]
        print(f"\nDecision: {rs.get('final_decision')} | PO: {rs.get('po_status')} "
              f"| exceptions: {rs.get('exception_count')} | routed_to: {rs.get('routed_to')}")
    return 0 if report.all_valid else 1


if __name__ == "__main__":
    raise SystemExit(_main())
